version: "3.8"
services:
  lightdash:
    env_file:
      - path: ./.env
    platform: linux/amd64
    # image: lightdash/lightdash:latest
    image: lightdash/lightdash:0.1116.0
    # weird bug latest build stalling pull.
    depends_on:
      - db
    environment:
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-postgres}
      - SECURE_COOKIES=${SECURE_COOKIES:-false}
      - TRUST_PROXY=${TRUST_PROXY:-false}
      - LIGHTDASH_SECRET=1234
      - PORT=${PORT:-8080}
      - LIGHTDASH_LOG_LEVEL=${LIGHTDASH_LOG_LEVEL}
      - LIGHTDASH_INSTALL_ID=${LIGHTDASH_INSTALL_ID}
      - LIGHTDASH_INSTALL_TYPE=${LIGHTDASH_INSTALL_TYPE:-docker_image}
      - AUTH_DISABLE_PASSWORD_AUTHENTICATION=${AUTH_DISABLE_PASSWORD_AUTHENTICATION}
      - AUTH_ENABLE_GROUP_SYNC=${AUTH_ENABLE_GROUP_SYNC}
      - AUTH_GOOGLE_ENABLED=${AUTH_GOOGLE_ENABLED}
      - AUTH_GOOGLE_OAUTH2_CLIENT_ID=${AUTH_GOOGLE_OAUTH2_CLIENT_ID}
      - AUTH_GOOGLE_OAUTH2_CLIENT_SECRET=${AUTH_GOOGLE_OAUTH2_CLIENT_SECRET}
      - SITE_URL=${SITE_URL}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_ALLOW_INVALID_CERT=${EMAIL_SMTP_ALLOW_INVALID_CERT}
      - EMAIL_SMTP_SENDER_NAME=${EMAIL_SMTP_SENDER_NAME}
      - EMAIL_SMTP_SENDER_EMAIL=${EMAIL_SMTP_SENDER_EMAIL}
      - ALLOW_MULTIPLE_ORGS=${ALLOW_MULTIPLE_ORGS:-false}
      - LIGHTDASH_QUERY_MAX_LIMIT=5000
      - LIGHTDASH_MAX_PAYLOAD=${LIGHTDASH_MAX_PAYLOAD:-5mb}
      - HEADLESS_BROWSER_HOST=headless-browser
      - HEADLESS_BROWSER_PORT=3000
      - RUDDERSTACK_WRITE_KEY=${RUDDERSTACK_WRITE_KEY}
      - SCHEDULER_ENABLED=true
      - GROUPS_ENABLED=${GROUPS_ENABLED:-false}
    volumes:
      - "${DBT_PROJECT_DIR}:/usr/app/dbt"
      - "${DBT_PROFILES_DIR}:/usr/app/profiles"
      - "${LIGHTDASH_CONFIG_FILE}:${LIGHTDASH_CONFIG_FILE}"
      

    ports:
      - ${PORT:-8080}:${PORT:-8080}
      # - '3000:3000'

  db:
    env_file:
      - path: ./.env
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_DB: ${PGDATABASE:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data

  headless-browser:
    env_file:
    - path: ./.env
    image: browserless/chrome:1-chrome-stable
    restart: always
    ports:
      - "3001:3000"

volumes:
  db-data:
