todo_analytics:
  outputs:
    duckdb:
      type: duckdb
      path: "{{env_var('DW_PATH')}}"
      threads: 12
      schema: main
    dev:
      type: postgres
      host: "boyluu0819.ddns.net"
      port: 5433
      user: "{{env_var('DW_USER')}}"
      password: "{{env_var('DW_PASSWORD')}}"
      dbname: "{{env_var('DW_DBNAME')}}"
      schema: dev
      sslmode: disable
      threads: 12

    prod:
      type: postgres
      host: "boyluu0819.ddns.net"
      port: 5433
      user: "{{env_var('DW_USER')}}"
      password: "{{env_var('DW_PASSWORD')}}"
      dbname: "{{env_var('DW_DBNAME')}}"
      schema: prod
      sslmode: disable
      threads: 12

  target: "{{env_var('TARGET_SCHEMA','dev')}}"