name: build usercode image

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
env: 
  RELEASE: ${{ vars.DOCKERHUB_USER }}/${{ vars.IMAGE_NAME }}

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Checkout DBT
        uses: actions/checkout@v4
        with:
          repository: luutuankiet/ticktick-py-dbt
          path: ./dbt

      - name: log in to dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ env.RELEASE }}:latest .


      - name: Test docker image
        run : echo "PLACEHOLDER"
      
      - name: Push docker image
        run: docker push ${{ env.RELEASE }}

  
