name: Update Server

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  update-server:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_HOST_KEY" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Update Server
      run: |
        # Add your commands here to update the server
        # Example: Replace the following with your deployment commands
        ssh root@boyluu96.ddns.net -p 15109 "cd /main/scrape_ticktick && git fetch origin main && git reset --hard origin/main && make deploy"
      env:
        SERVER_HOST_KEY: ${{ secrets.SERVER_HOST_KEY }}
