name: deploy-lightdash

on:
  push:
    branches: [ "main", "master" ]

env:
  DBT_VERSION: "1.8.1"
  TARGET_SCHEMA: "prod"
  # PROJECT_DIR: "./dbt_project"
  # DW_DBNAME: "gtd_dash"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Bootstrap environment variables
        id: load-env
        run: |
          # First step: initialize the file
          . ./bootstrap_env.sh

          # Check if .env.bootstrap file exists
          if [ -f .env.bootstrap ]; then
            # Process each line in the .env.bootstrap file
            while IFS= read -r line; do
              # Skip empty lines and lines starting with #
              if [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
                # Export the variable to $GITHUB_ENV, removing surrounding quotes if present
                clean_line=$(echo "$line" | awk -F= '{print $1 "=" substr($2, 2, length($2)-2)}')
                echo "$clean_line" >> $GITHUB_ENV
              fi
            done < .env.bootstrap
          else
            echo ".env.bootstrap file not found"
          fi

      - name: Create .env file from secret
        run: |
          # Decode and create .env file
          echo "$PROD_ENV" > .env
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}          

      - name: Dynamically Mask Environment Variables
        id: mask-env
        run: |
          # Read the .env file line by line
          while IFS= read -r line; do
            # Skip empty lines and lines starting with #
            if [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
              # Extract variable name and value
              var_name=$(echo "$line" | awk -F= '{print $1}')
              var_value=$(echo "$line" | awk -F= '{print $2}' | sed 's/^"\(.*\)"$/\1/')

              # Mask the variable value
              echo "::add-mask::$var_value"

              # Export the variable to $GITHUB_ENV without quotes
              clean_line="$var_name=$var_value"
              echo "$clean_line" >> "$GITHUB_ENV"
            fi
          done < .env
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}


      # Cache Python packages
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install dbt-core==$DBT_VERSION dbt-postgres==$DBT_VERSION
          dbt deps --project-dir $DBT_PROJECT_DIR

      # Cache npm packages
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/setup-node@v3.4.1

      - name: Copy Google credentials file
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        if: "${{ env.GOOGLE_CREDENTIALS != '' }}"
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "googlecredentials.json"
          json: ${{ env.GOOGLE_CREDENTIALS }}

      - name: Move credentials to /tmp 
        run: mv googlecredentials.json /tmp || true


      - name: Get lightdash version 
        uses: sergeysova/jq-action@v2
        id: version 
        env:
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}   
        with: 
          cmd: curl -s "${LIGHTDASH_URL}/api/v1/health" | jq -r '.results.version'

      - name: Copy profiles.yml
        env:
          config: ${{ secrets.DBT_PROFILES }}          
        run: echo -e "$config" > profiles.yml      

      - name: Install lightdash CLI
        run: npm install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || npm install -g @lightdash/cli@latest

      - name: Lightdash CLI deploy 
        env:
          LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}          
          LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}          
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}      
          GOOGLE_APPLICATION_CREDENTIALS: '/tmp/googlecredentials.json'    
        run: lightdash deploy --project-dir $DBT_PROJECT_DIR --profiles-dir . --profile prod || lightdash deploy --project-dir $DBT_PROJECT_DIR --profiles-dir $DBT_PROFILES_DIR
