name: helloworld

on: 
    workflow_dispatch: 

jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: helloworld
              run: echo "hello world. event is $GITHUB_OBJ"
              env: 
                    GITHUB_OBJ: ${{ github }}
